function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonnegatives, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.048389416
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.SingleVariable,MathOptInterface.AbstractScalarSet})   # time: 0.03299137
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}} where {T, F<:MathOptInterface.SingleVariable}})   # time: 0.02840943
    Base.precompile(Tuple{typeof(has_bridges),Map})   # time: 0.013614236
    Base.precompile(Tuple{typeof(variable_constraints),Map,MathOptInterface.VariableIndex})   # time: 0.010480635
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constrained_variable_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}}})   # time: 0.007661137
    Base.precompile(Tuple{typeof(empty!),Map})   # time: 0.007576335
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{SplitIntervalBridge{Float64, MathOptInterface.SingleVariable, MathOptInterface.Interval{Float64}, MathOptInterface.GreaterThan{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.007041929
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{SquareBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeTriangle, MathOptInterface.PositiveSemidefiniteConeSquare}}})   # time: 0.006890723
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constrained_variable_types),Type{VectorSlackBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeSquare}}})   # time: 0.006461247
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constrained_variable_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}}})   # time: 0.006377854
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{SquareBridge{Float64, MathOptInterface.VectorOfVariables, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeTriangle, MathOptInterface.PositiveSemidefiniteConeSquare}}})   # time: 0.006344027
    # TODO: Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{T}}})   # time: 0.005965137
    # TODO: Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.LessThan{T}}})   # time: 0.005906573
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorFunctionizeBridge{Float64, MathOptInterface.Nonpositives}}})   # time: 0.005836183
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{SplitIntervalBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}, MathOptInterface.GreaterThan{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.005833324
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarizeBridge{Float64, MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}}})   # time: 0.005829607
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{SplitIntervalBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}, MathOptInterface.GreaterThan{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.005761993
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{GreaterToIntervalBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.00575148
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorFunctionizeBridge{Float64, MathOptInterface.PositiveSemidefiniteConeSquare}}})   # time: 0.00574405
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarFunctionizeBridge{Float64, MathOptInterface.GreaterThan{Float64}}}})   # time: 0.00567841
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarFunctionizeBridge{Float64, MathOptInterface.LessThan{Float64}}}})   # time: 0.005579188
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonnegatives, MathOptInterface.SingleVariable}}})   # time: 0.005479757
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{NonposToNonnegBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.VectorAffineFunction{Float64}}}})   # time: 0.00540064
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarizeBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.005361762
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{LessToGreaterBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.SingleVariable}}})   # time: 0.00535649
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constrained_variable_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.005323451
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constrained_variable_types),Type{VectorSlackBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonpositives}}})   # time: 0.005278666
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{NonnegToNonposBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.VectorOfVariables}}})   # time: 0.005213201
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Zeros, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.005212731
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonpositives, MathOptInterface.SingleVariable}}})   # time: 0.00519287
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarizeBridge{Float64, MathOptInterface.SingleVariable, MathOptInterface.LessThan{Float64}}}})   # time: 0.005168288
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorFunctionizeBridge{Float64, MathOptInterface.Nonnegatives}}})   # time: 0.00512054
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{GreaterToLessBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.005100022
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{NonposToNonnegBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.VectorOfVariables}}})   # time: 0.005093382
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{LessToIntervalBridge{Float64, MathOptInterface.SingleVariable}}})   # time: 0.005061132
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{LessToIntervalBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.005032025
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{GreaterToLessBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.SingleVariable}}})   # time: 0.005014173
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{GreaterToIntervalBridge{Float64, MathOptInterface.SingleVariable}}})   # time: 0.004949188
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonpositives, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.00493602
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarFunctionizeBridge{Float64, MathOptInterface.Interval{Float64}}}})   # time: 0.00493321
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{LessToGreaterBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ScalarAffineFunction{Float64}}}})   # time: 0.004918501
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}})   # time: 0.004912217
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorFunctionizeBridge{Float64, MathOptInterface.PositiveSemidefiniteConeTriangle}}})   # time: 0.004706224
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, _A} where _A})   # time: 0.003971573
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}} where {T, F<:Union{MathOptInterface.SingleVariable, MathOptInterface.VectorOfVariables}}})   # time: 0.003837313
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorOfVariables,MathOptInterface.AbstractVectorSet})   # time: 0.003170592
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}} where {T, F<:MathOptInterface.SingleVariable}})   # time: 0.002960819
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonnegatives, MathOptInterface.SingleVariable},MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}})   # time: 0.002900157
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}} where {T, F<:Union{MathOptInterface.SingleVariable, MathOptInterface.VectorOfVariables}}})   # time: 0.00279975
    Base.precompile(Tuple{typeof(haskey),Map,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.002708187
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Zeros, MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}})   # time: 0.002476458
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,VectorizeBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonnegatives, MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}})   # time: 0.002441077
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,SquareBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeTriangle, MathOptInterface.PositiveSemidefiniteConeSquare},MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.PositiveSemidefiniteConeSquare})   # time: 0.00238164
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,VectorFunctionizeBridge{Float64, MathOptInterface.PositiveSemidefiniteConeTriangle},MathOptInterface.VectorOfVariables,MathOptInterface.PositiveSemidefiniteConeTriangle})   # time: 0.002314156
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorSlackBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeSquare}}})   # time: 0.002269375
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,LessToGreaterBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}})   # time: 0.002267911
    Base.precompile(Tuple{typeof(haskey),Map,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F}})   # time: 0.00218399
    Base.precompile(Tuple{typeof(vector_of_variables_constraints),Map})   # time: 0.001941289
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}})   # time: 0.001907838
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}}})   # time: 0.0017095
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorOfVariables,MathOptInterface.AbstractSet})   # time: 0.001644976
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.SingleVariable,MathOptInterface.AbstractSet})   # time: 0.001513536
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.AbstractSet})   # time: 0.001489506
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}}})   # time: 0.00147503
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{ScalarSlackBridge{Float64, MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}}})   # time: 0.001448391
    # TODO: Base.precompile(Tuple{typeof(delete!),Map,Union{MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.LessThan{T}}}})   # time: 0.001438713
    Base.precompile(Tuple{typeof(MathOptInterface.Bridges.added_constraint_types),Type{VectorSlackBridge{Float64, MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonpositives}}})   # time: 0.001423358
    Base.precompile(Tuple{typeof(haskey),Map,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S} where S})   # time: 0.001388763
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}})   # time: 0.001372888
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.AbstractFunction,MathOptInterface.AbstractSet})   # time: 0.001332999
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.ScalarAffineFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.AbstractSet})   # time: 0.001300738
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Zeros})   # time: 0.001159031
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.SecondOrderCone})   # time: 0.001082412
    Base.precompile(Tuple{typeof(delete!),Map,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.001056021
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Nonnegatives})   # time: 0.001055006
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.PositiveSemidefiniteConeSquare})   # time: 0.00105328
    Base.precompile(Tuple{typeof(add_key_for_bridge),Map,AbstractBridge,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.PositiveSemidefiniteConeTriangle})   # time: 0.001016888
end
