function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    isdefined(MathOptInterface.Utilities, Symbol("#165#171")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#165#171")),DataType})   # time: 1.4558948
    Base.precompile(Tuple{typeof(broadcastvcat),Function,Model{Float64}})   # time: 1.4121648
    Base.precompile(Tuple{typeof(MathOptInterface.delete),UniversalFallback{Model{Float64}},MathOptInterface.VariableIndex})   # time: 1.1493027
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraints})   # time: 0.21186654
    Base.precompile(Tuple{typeof(MathOptInterface.empty!),UniversalFallback{Model{Float64}}})   # time: 0.122432366
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeSquare}})   # time: 0.12199785
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.VectorOfVariables, MathOptInterface.PositiveSemidefiniteConeTriangle}})   # time: 0.10004706
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.VectorOfVariables,MathOptInterface.AbstractVectorSet})   # time: 0.099981986
    Base.precompile(Tuple{typeof(keys),IndexMap})   # time: 0.09508495
    Base.precompile(Tuple{typeof(MathOptInterface.optimize!),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}}})   # time: 0.08862922
    Base.precompile(Tuple{typeof(operate),typeof(*),Type{Float64},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.079366356
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.VectorAffineFunction{Float64}})   # time: 0.07101885
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.062484402
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfVariableIndices})   # time: 0.056865256
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.ScalarQuadraticFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.055448838
    # TODO: Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorAffineFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.049536582
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Type{Float64},Int64,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.04774441
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.SecondOrderCone}})   # time: 0.04695538
    # TODO: Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorQuadraticFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.045612343
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.04524842
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}})   # time: 0.04296505
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.LazyConstraintCallback,Function})   # time: 0.04126309
    Base.precompile(Tuple{typeof(MathOptInterface.modify),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarCoefficientChange{Float64}})   # time: 0.037959184
    Base.precompile(Tuple{typeof(map_indices),Function,MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.03368791
    Base.precompile(Tuple{typeof(delete!),IndexMap,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.03231516
    Base.precompile(Tuple{typeof(MathOptInterface.add_variables),UniversalFallback{Model{Float64}},Any})   # time: 0.031159803
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.ScalarAffineFunction{MathOptInterface.ScalarAffineFunction{Float64}}})   # time: 0.03082883
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfVariableAttributesSet})   # time: 0.029612781
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.SingleVariable,MathOptInterface.AbstractScalarSet})   # time: 0.027166696
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.DualStatus})   # time: 0.026211431
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.PrimalStatus})   # time: 0.025897125
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.Silent,Bool})   # time: 0.025886275
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.025841229
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{_A, _B} where {_A, _B}})   # time: 0.025434624
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.VariableName,MathOptInterface.VariableIndex,String})   # time: 0.02458812
    Base.precompile(Tuple{typeof(operate),typeof(-),Type{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.SingleVariable})   # time: 0.023819331
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.VectorOfVariables})   # time: 0.023671608
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.Interval{Float64}}})   # time: 0.020710003
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}},String})   # time: 0.020317951
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.AbstractFunction,MathOptInterface.AbstractSet})   # time: 0.020015607
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.ScalarAffineFunction{_A} where _A,MathOptInterface.AbstractSet})   # time: 0.019851033
    Base.precompile(Tuple{typeof(MathOptInterface.delete),UniversalFallback{Model{Float64}},Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.018373866
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.ScalarAffineFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.AbstractSet})   # time: 0.016342334
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintSet,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{T}} where T})   # time: 0.014742568
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.PositiveSemidefiniteConeTriangle})   # time: 0.012966506
    Base.precompile(Tuple{typeof(getindex),ScalarFunctionIterator{MathOptInterface.VectorAffineFunction{Float64}},Int64})   # time: 0.012782512
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.AbstractScalarFunction})   # time: 0.011779644
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.LessThan{T}} where T})   # time: 0.01177635
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.AbstractSet})   # time: 0.011083066
    # TODO: Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)},T<:(MathOptInterface.ScalarAffineFunction{_A} where _A),MathOptInterface.SingleVariable})   # time: 0.010697476
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{T}} where T})   # time: 0.010508736
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S} where S})   # time: 0.009982171
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.009751869
    Base.precompile(Tuple{typeof(MathOptInterface.delete),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S} where S})   # time: 0.009529631
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}},String})   # time: 0.009372859
    Base.precompile(Tuple{typeof(getindex),ScalarFunctionIterator{MathOptInterface.VectorAffineFunction{Float64}},Vector{Int64}})   # time: 0.009297068
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.NLPBlock,MathOptInterface.NLPBlockData})   # time: 0.009188253
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ObjectiveSense,MathOptInterface.OptimizationSense})   # time: 0.009152894
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.ScalarAffineFunction{_A} where _A})   # time: 0.008855449
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}},String})   # time: 0.008473215
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.UserCutCallback,Function})   # time: 0.00811491
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfModelAttributesSet})   # time: 0.008045145
    # TODO: Base.precompile(Tuple{typeof(setindex!),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S},MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S}})   # time: 0.007972478
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.SingleVariable}})   # time: 0.007827095
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.HeuristicCallback,Function})   # time: 0.007820415
    Base.precompile(Tuple{typeof(map_indices),Function,MathOptInterface.ScalarQuadraticTerm{Float64}})   # time: 0.007779868
    # TODO: Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.ScalarAffineFunction{T},MathOptInterface.SingleVariable})   # time: 0.007589532
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F}})   # time: 0.007550623
    Base.precompile(Tuple{typeof(MathOptInterface.set),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction,MathOptInterface.ScalarAffineFunction{_A} where _A})   # time: 0.007418556
    Base.precompile(Tuple{typeof(map_indices),Function,MathOptInterface.ScalarQuadraticFunction{Float64}})   # time: 0.006926228
    Base.precompile(Tuple{typeof(map_indices),IndexMap,Vector{MathOptInterface.VariableIndex}})   # time: 0.006504927
    Base.precompile(Tuple{typeof(map_indices),Function,MathOptInterface.VectorAffineFunction{Float64}})   # time: 0.006169203
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, _A} where _A})   # time: 0.006143256
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarQuadraticFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.006133721
    # TODO: Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)},Int64,MathOptInterface.VectorAffineFunction{T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)},T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)})   # time: 0.005806269
    isdefined(MathOptInterface.Utilities, Symbol("#166#172")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#166#172")),DataType})   # time: 0.005533174
    Base.precompile(Tuple{typeof(operate!),typeof(+),Type{Float64},MathOptInterface.ScalarQuadraticFunction{Float64},MathOptInterface.ScalarQuadraticFunction{Float64}})   # time: 0.005454123
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfOptimizerAttributesSet})   # time: 0.005238003
    Base.precompile(Tuple{typeof(delete!),IndexMap,MathOptInterface.VariableIndex})   # time: 0.005049041
    Base.precompile(Tuple{typeof(MathOptInterface.delete),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, S} where S})   # time: 0.00496782
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintFunction,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S} where S})   # time: 0.004443296
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.AbstractOptimizerAttribute})   # time: 0.004368742
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{_A, _B} where {_A, _B}})   # time: 0.0043292
    # TODO: Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}},MathOptInterface.AbstractScalarSet})   # time: 0.004154197
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}})   # time: 0.004114619
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ObjectiveFunction{MathOptInterface.SingleVariable},MathOptInterface.SingleVariable})   # time: 0.004089465
    Base.precompile(Tuple{typeof(operate!),typeof(+),Type{Float64},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.004055656
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.003774213
    Base.precompile(Tuple{typeof(getindex),IndexMap,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F<:MathOptInterface.AbstractScalarFunction}})   # time: 0.003678685
    Base.precompile(Tuple{typeof(operate),typeof(*),Type{Float64},Float64,MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.003466153
    Base.precompile(Tuple{typeof(operate!),typeof(*),Type{Float64},MathOptInterface.ScalarQuadraticFunction{Float64},Float64})   # time: 0.003435623
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.VectorOfVariables,MathOptInterface.Nonnegatives})   # time: 0.003421846
    Base.precompile(Tuple{typeof(MathOptInterface.set),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction,MathOptInterface.AbstractScalarFunction})   # time: 0.003342248
    Base.precompile(Tuple{typeof(isapprox_zero),MathOptInterface.ScalarAffineFunction{Float64},Float64})   # time: 0.003337314
    Base.precompile(Tuple{typeof(operate!),typeof(+),Type{Float64},MathOptInterface.ScalarQuadraticFunction{Float64},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.003279901
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.003153471
    Base.precompile(Tuple{typeof(getindex),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S} where S})   # time: 0.003147332
    Base.precompile(Tuple{typeof(MathOptInterface.is_valid),UniversalFallback{Model{Float64}},MathOptInterface.VariableIndex})   # time: 0.003063951
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}})   # time: 0.003004704
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Nonnegatives})   # time: 0.002920673
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.SingleVariable, MathOptInterface.LessThan{Float64}}})   # time: 0.002901544
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.SingleVariable, MathOptInterface.EqualTo{Float64}}})   # time: 0.002896252
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.SingleVariable, MathOptInterface.ZeroOne}})   # time: 0.002891152
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.SingleVariable, MathOptInterface.Integer}})   # time: 0.002888883
    Base.precompile(Tuple{typeof(MathOptInterface.modify),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}},MathOptInterface.ScalarCoefficientChange{Float64}})   # time: 0.002811431
    Base.precompile(Tuple{typeof(MathOptInterface.add_constraint),UniversalFallback{Model{Float64}},MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Zeros})   # time: 0.002725057
    Base.precompile(Tuple{typeof(MathOptInterface.set),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.002560265
    Base.precompile(Tuple{typeof(index_map_for_variable_indices),Vector{MathOptInterface.VariableIndex}})   # time: 0.002516896
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.NLPBlock})   # time: 0.002506225
    Base.precompile(Tuple{typeof(haskey),IndexMap,MathOptInterface.ConstraintIndex})   # time: 0.002464554
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.HeuristicCallback})   # time: 0.002410447
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.LazyConstraintCallback})   # time: 0.002387894
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintSet,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, MathOptInterface.PositiveSemidefiniteConeTriangle}})   # time: 0.002289546
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),MathOptInterface.ScalarAffineFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.AbstractScalarSet})   # time: 0.002264879
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.Integer}})   # time: 0.002199597
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.Semicontinuous{Float64}}})   # time: 0.002120947
    Base.precompile(Tuple{typeof(delete!),IndexMap,MathOptInterface.ConstraintIndex{_A, _B} where {_A, _B}})   # time: 0.002118063
    # TODO: Base.precompile(Tuple{typeof(setindex!),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, S},MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, S}})   # time: 0.002073167
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.Semiinteger{Float64}}})   # time: 0.002064088
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.GreaterThan{Float64}}})   # time: 0.002040845
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.UserCutCallback})   # time: 0.002039284
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),Any})   # time: 0.002022543
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeSquare}})   # time: 0.002003081
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.ZeroOne}})   # time: 0.001982808
    Base.precompile(Tuple{typeof(_add_contraint_type),Vector{Tuple{DataType, DataType}},Model{Float64},Type{MathOptInterface.LessThan{Float64}}})   # time: 0.001954173
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.VariableBridgingCost})   # time: 0.001767792
    Base.precompile(Tuple{typeof(getindex),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, S} where S})   # time: 0.00175013
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.SecondOrderCone}})   # time: 0.001641073
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.ScalarQuadraticFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.001637458
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.VectorOfVariables, MathOptInterface.PositiveSemidefiniteConeTriangle}})   # time: 0.001616716
    Base.precompile(Tuple{typeof(operate),typeof(-),Type{Float64},MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.SingleVariable})   # time: 0.001598086
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}})   # time: 0.001546691
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintSet,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.EqualTo{Float64}}})   # time: 0.001534907
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}})   # time: 0.001512601
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.SingleVariable, MathOptInterface.GreaterThan{Float64}}})   # time: 0.001501434
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.PositiveSemidefiniteConeSquare}})   # time: 0.001470739
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.001470722
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.SingleVariable, MathOptInterface.ZeroOne}})   # time: 0.001447509
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.VariableName,MathOptInterface.VariableIndex})   # time: 0.001442049
    # TODO: Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)},Int64,MathOptInterface.VectorQuadraticFunction{T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)},T<:(MathOptInterface.ScalarAffineFunction{_A} where _A)})   # time: 0.001415966
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.SingleVariable, MathOptInterface.Integer}})   # time: 0.001401716
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.SingleVariable, MathOptInterface.EqualTo{Float64}}})   # time: 0.001396837
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.00138956
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet{MathOptInterface.SingleVariable, MathOptInterface.LessThan{Float64}}})   # time: 0.001385637
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}}})   # time: 0.001348312
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.ScalarQuadraticFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.001345947
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.SecondOrderCone}})   # time: 0.001335296
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, MathOptInterface.PositiveSemidefiniteConeTriangle}})   # time: 0.00123058
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}})   # time: 0.001227755
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.AbstractScalarSet})   # time: 0.001179703
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.ConstraintName,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.LessThan{Float64}}})   # time: 0.001132447
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.001115607
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.ZeroOne}})   # time: 0.001113076
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}})   # time: 0.001087792
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.Integer}})   # time: 0.001086164
    Base.precompile(Tuple{typeof(MathOptInterface.get),CachingOptimizer{MathOptInterface.AbstractOptimizer, UniversalFallback{Model{Float64}}},MathOptInterface.NumberOfVariables})   # time: 0.001085694
    isdefined(MathOptInterface.Utilities, Symbol("#145#147")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#145#147")),MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable, MathOptInterface.LessThan{Float64}}})   # time: 0.001064242
    Base.precompile(Tuple{typeof(getindex),IndexMap,Union{MathOptInterface.ConstraintIndex{F, MathOptInterface.GreaterThan{T}}, MathOptInterface.ConstraintIndex{F, MathOptInterface.LessThan{T}}} where {T, F}})   # time: 0.001060553
    isdefined(MathOptInterface.Utilities, Symbol("#166#172")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#166#172")),Type})   # time: 0.00104939
end
