name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.moi_test_modules }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Since MOI doesn't have binary dependencies, only test on a subset of
        # possible platforms.
        include:
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'General;Nonlinear;Bridges;FileFormats'
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'Test;Utilities;Benchmarks'
          - version: '1'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'General;Nonlinear;Bridges;FileFormats'
          - version: '1'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'Test;Utilities;Benchmarks'
          - version: '1'
            os: windows-latest
            arch: x64
            moi_test_modules: 'General;Nonlinear;Bridges;FileFormats'
          - version: '1'
            os: windows-latest
            arch: x64
            moi_test_modules: 'Test;Utilities;Benchmarks'
          - version: '1.6'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'General;Nonlinear;Bridges;FileFormats'
          - version: '1.6'
            os: ubuntu-latest
            arch: x64
            moi_test_modules: 'Test;Utilities;Benchmarks'
          - version: '1'
            os: ubuntu-latest
            arch: x86
            moi_test_modules: 'General;Nonlinear;Bridges;FileFormats'
          - version: '1'
            os: ubuntu-latest
            arch: x86
            moi_test_modules: 'Test;Utilities;Benchmarks'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
            MOI_TEST_MODULES: ${{ matrix.moi_test_modules }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
