name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.group }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        group: ["base;Benchmarks;FileFormats;Nonlinear", "Bridges", "Test", "Utilities"]
        version: ['1.6', '1', 'nightly']
        os: ['ubuntu-latest', 'windows-latest']
        arch: ['x86', 'x64']
        exclude:
          - os: ubuntu-latest
            version: '1'
            arch: x86
          - os: ubuntu-latest
            version: 'nightly'
            arch: x86
          - os: windows-latest
            arch: x86
          - os: windows-latest
            version: '1.6'
          - os: windows-latest
            version: 'nightly'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_TEST_MATHOPTINTERFACE: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
